from algorithms.SELO import socio_evolution_learning_optimization
from algorithms.PSO import particle_swarm_optimization
from algorithms.NPO import nomadic_people_optimizer
from algorithms.SNLO import socio_nomadic_learning_optimizer
from algorithms.ABC import artificial_bee_colony
from algorithms.HGS import hunger_games_search